---
# FIXME-travis-postgres: see https://github.com/travis-ci/travis-ci/issues/8537

dist: trusty
env:
  global:
  - PGPORT=5433  # FIXME-travis-postgres (rm this line)
  - TRAVIS=True
  - CI=True
language: python
python:
  - 3.6
services:
  - postgresql

# FIXME-travis-postgres (hopefully delete the entire addons block)
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_install:
  - sudo apt-get update -q
  - sudo apt-get install postfix

  # FIXME-travis-postgres (rm next 2 lines)
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart

install:
  - pip install tox-travis

before_script:
  - psql -c "CREATE DATABASE flask_test;" -U postgres
  - psql -c "CREATE USER flask_test WITH PASSWORD 'flask_test';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE flask_test TO flask_test;" -U postgres

script:
  - tox -c .travis.tox.ini
